//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LfServiceReniecCliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaLogin", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceReniec")]
    [System.SerializableAttribute()]
    public partial class ConsultaLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasennaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenna {
            get {
                return this.ContrasennaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasennaField, value) != true)) {
                    this.ContrasennaField = value;
                    this.RaisePropertyChanged("Contrasenna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegSede", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceReniec")]
    [System.SerializableAttribute()]
    public partial class RegSede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegId {
            get {
                return this.RegIdField;
            }
            set {
                if ((this.RegIdField.Equals(value) != true)) {
                    this.RegIdField = value;
                    this.RaisePropertyChanged("RegId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceReniec")]
    public interface IServiceReniec {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/validaruser", ReplyAction="http://tempuri.org/IServiceReniec/validaruserResponse")]
        string validaruser(LfServiceReniecCliente.ServiceReference1.ConsultaLogin loginfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/validaruser", ReplyAction="http://tempuri.org/IServiceReniec/validaruserResponse")]
        System.Threading.Tasks.Task<string> validaruserAsync(LfServiceReniecCliente.ServiceReference1.ConsultaLogin loginfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/RegistrartUsuario", ReplyAction="http://tempuri.org/IServiceReniec/RegistrartUsuarioResponse")]
        string RegistrartUsuario(LfServiceReniecCliente.ServiceReference1.ConsultaLogin userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/RegistrartUsuario", ReplyAction="http://tempuri.org/IServiceReniec/RegistrartUsuarioResponse")]
        System.Threading.Tasks.Task<string> RegistrartUsuarioAsync(LfServiceReniecCliente.ServiceReference1.ConsultaLogin userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/InsertUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/InsertUserRegDetailsResponse")]
        string InsertUserRegDetails(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/InsertUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/InsertUserRegDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertUserRegDetailsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/GetUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/GetUserRegDetailsResponse")]
        System.Data.DataSet GetUserRegDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/GetUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/GetUserRegDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserRegDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IServiceReniec/FetchUpdatedRecordsResponse")]
        System.Data.DataSet FetchUpdatedRecords(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IServiceReniec/FetchUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/UpdateUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/UpdateUserRegDetailsResponse")]
        string UpdateUserRegDetails(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/UpdateUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/UpdateUserRegDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateUserRegDetailsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/DeleteUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/DeleteUserRegDetailsResponse")]
        bool DeleteUserRegDetails(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/DeleteUserRegDetails", ReplyAction="http://tempuri.org/IServiceReniec/DeleteUserRegDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserRegDetailsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/BuscarNombreSede", ReplyAction="http://tempuri.org/IServiceReniec/BuscarNombreSedeResponse")]
        System.Data.DataSet BuscarNombreSede(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/BuscarNombreSede", ReplyAction="http://tempuri.org/IServiceReniec/BuscarNombreSedeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarNombreSedeAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/BuscarDireccionSede", ReplyAction="http://tempuri.org/IServiceReniec/BuscarDireccionSedeResponse")]
        System.Data.DataSet BuscarDireccionSede(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReniec/BuscarDireccionSede", ReplyAction="http://tempuri.org/IServiceReniec/BuscarDireccionSedeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarDireccionSedeAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceReniecChannel : LfServiceReniecCliente.ServiceReference1.IServiceReniec, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceReniecClient : System.ServiceModel.ClientBase<LfServiceReniecCliente.ServiceReference1.IServiceReniec>, LfServiceReniecCliente.ServiceReference1.IServiceReniec {
        
        public ServiceReniecClient() {
        }
        
        public ServiceReniecClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceReniecClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReniecClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReniecClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validaruser(LfServiceReniecCliente.ServiceReference1.ConsultaLogin loginfo) {
            return base.Channel.validaruser(loginfo);
        }
        
        public System.Threading.Tasks.Task<string> validaruserAsync(LfServiceReniecCliente.ServiceReference1.ConsultaLogin loginfo) {
            return base.Channel.validaruserAsync(loginfo);
        }
        
        public string RegistrartUsuario(LfServiceReniecCliente.ServiceReference1.ConsultaLogin userInfo) {
            return base.Channel.RegistrartUsuario(userInfo);
        }
        
        public System.Threading.Tasks.Task<string> RegistrartUsuarioAsync(LfServiceReniecCliente.ServiceReference1.ConsultaLogin userInfo) {
            return base.Channel.RegistrartUsuarioAsync(userInfo);
        }
        
        public string InsertUserRegDetails(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.InsertUserRegDetails(regdet);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserRegDetailsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.InsertUserRegDetailsAsync(regdet);
        }
        
        public System.Data.DataSet GetUserRegDetails() {
            return base.Channel.GetUserRegDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserRegDetailsAsync() {
            return base.Channel.GetUserRegDetailsAsync();
        }
        
        public System.Data.DataSet FetchUpdatedRecords(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.FetchUpdatedRecords(regdet);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.FetchUpdatedRecordsAsync(regdet);
        }
        
        public string UpdateUserRegDetails(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.UpdateUserRegDetails(regdet);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserRegDetailsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.UpdateUserRegDetailsAsync(regdet);
        }
        
        public bool DeleteUserRegDetails(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.DeleteUserRegDetails(regdet);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserRegDetailsAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.DeleteUserRegDetailsAsync(regdet);
        }
        
        public System.Data.DataSet BuscarNombreSede(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.BuscarNombreSede(regdet);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarNombreSedeAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.BuscarNombreSedeAsync(regdet);
        }
        
        public System.Data.DataSet BuscarDireccionSede(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.BuscarDireccionSede(regdet);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarDireccionSedeAsync(LfServiceReniecCliente.ServiceReference1.RegSede regdet) {
            return base.Channel.BuscarDireccionSedeAsync(regdet);
        }
    }
}
